[package]
name = "tensorflow-protos"
version = "0.1.0"
authors = ["Josh Kurland <joshua.kurland@outlook.com>"]
edition = "2018"

[dependencies]
protobuf = "2.5.0"

[build-dependencies]
protobuf-codegen-pure = "2.3"